In [1]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
from IPython.display import display, Markdown

import pandas as pd
import numpy as np

import json

np.__version__

'1.23.4'

In [2]:
USEFUL_COLUMNS = ['chart_position', 'song', 'performer', 'song_id']
hot_100_raw = pd.read_csv('./data/Hot 100 through 2022.csv')[USEFUL_COLUMNS]
hot_100_raw

,chart_position,song,performer,song_id
0,84,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless"
1,78,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless"
2,68,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless"
3,60,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless"
4,58,"""B"" Girls",Young And Restless,"""B"" GirlsYoung And Restless"
...,...,...,...,...
336290,99,www.memory,Alan Jackson,www.memoryAlan Jackson
336291,66,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,¿Dònde Està Santa Claus? (Where Is Santa Claus...
336292,53,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,¿Dònde Està Santa Claus? (Where Is Santa Claus...
336293,47,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,¿Dònde Està Santa Claus? (Where Is Santa Claus...
336294,47,¿Dònde Està Santa Claus? (Where Is Santa Claus?),Augie Rios,¿Dònde Està Santa Claus? (Where Is Santa Claus...

In [3]:
SONG_RANKING_FILTER_THRESHOLD = 10
top_10 = hot_100_raw[
    hot_100_raw.chart_position <= SONG_RANKING_FILTER_THRESHOLD
].copy()
top_10['score_for_that_week'] = top_10.chart_position.apply(lambda chart_position: 11 - chart_position)
top_10

,chart_position,song,performer,song_id,score_for_that_week
92,10,#9 Dream,John Lennon,#9 DreamJohn Lennon,1
93,9,#9 Dream,John Lennon,#9 DreamJohn Lennon,2
164,8,'03 Bonnie & Clyde,Jay-Z Featuring Beyonce Knowles,'03 Bonnie & ClydeJay-Z Featuring Beyonce Knowles,3
165,6,'03 Bonnie & Clyde,Jay-Z Featuring Beyonce Knowles,'03 Bonnie & ClydeJay-Z Featuring Beyonce Knowles,5
166,5,'03 Bonnie & Clyde,Jay-Z Featuring Beyonce Knowles,'03 Bonnie & ClydeJay-Z Featuring Beyonce Knowles,6
...,...,...,...,...,...
336128,8,iSpy,KYLE Featuring Lil Yachty,iSpyKYLE Featuring Lil Yachty,3
336129,10,iSpy,KYLE Featuring Lil Yachty,iSpyKYLE Featuring Lil Yachty,1
336171,8,interlude,J. Cole,interludeJ. Cole,3
336179,2,my.life,"J. Cole, 21 Savage & Morray","my.lifeJ. Cole, 21 Savage & Morray",9
336213,7,pride.is.the.devil,J. Cole & Lil Baby,pride.is.the.devilJ. Cole & Lil Baby,4

In [4]:
popularity_score_df = top_10.groupby(['song', 'performer']).sum()['score_for_that_week'].reset_index().rename(
    columns={'score_for_that_week': 'popularity_score'}
)
popularity_score_df.sort_values('popularity_score')

,song,performer,popularity_score
2818,Mirage,Tommy James And The Shondells,1
1553,Happy-Go-Lucky-Me,Paul Evans,1
3347,Put Your Hands Together,The O'Jays,1
614,Call Me (Come Back Home),Al Green,1
1545,Hanky Panky,Madonna,1
...,...,...,...
731,Closer,The Chainsmokers Featuring Halsey,246
4591,Uptown Funk!,Mark Ronson Featuring Bruno Mars,251
293,As It Was,Harry Styles,287
3886,Stay,The Kid LAROI & Justin Bieber,325
486,Blinding Lights,The Weeknd,375

In [5]:
popularity_score_df.to_csv('./data/21-OUTPUT-scored-with-sum-of-popularity-over-time.csv', index=False)